on: [push]

name: Build and release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout_source
      uses: actions/checkout@v1

    - name: Install jq
      id: install_jq    
      run: sudo apt-get install jq

    - name: Read version.json into output variable
      id: read_version_json
      run: echo ::set-output name=json::$(cat ./version.json | jq '.')

    - name: Read MOD version into output variable
      id: read_mod_version
      run: echo ::set-output name=version::$(cat ./version.json | jq -r '.modVersion')

    - name: Read MC version into output variable
      id: read_mc_version
      run: echo ::set-output name=version::$(cat ./version.json | jq -r '.minecraftVersion')

    - name: Setup JDK 1.8
      id: init_jdk
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Display the path
      id: ls_path
      run: ls -la
      shell: bash

    - name: Make gradlew executable
      id: make_gradle_executable
      run: chmod +x ./gradlew
      shell: bash

    - name: Delete gradle.properties
      id: delete_gradle_properties
      run: rm ./gradle.properties
      shell: bash

    - name: Build with Gradle
      id: build_gradle
      run: ./gradlew build

    - name: Do SonarQube analysis
      id: sonar_analysis
      run: ./gradlew sonarqube
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}        

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ steps.read_mod_version.outputs.version }} - ${{ github.sha }}
        draft: true
        prerelease: false

    - name: Upload Release Asset
      id: upload_release_asset    
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./build/libs/BasseBombeCraft-${{ steps.read_mc_version.outputs.version }}-${{ steps.read_mod_version.outputs.version }}.jar
        asset_name: BasseBombeCraft-${{ steps.read_mc_version.outputs.version }}-${{ steps.read_mod_version.outputs.version }}.jar
        asset_content_type: application/zip

    - name: Upload Release Asset
      id: upload_release_asset    
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./build/libs/BasseBombeCraft-${{ steps.read_mc_version.outputs.version }}-${{ steps.read_mod_version.outputs.version }}-server.jar
        asset_name: BasseBombeCraft-${{ steps.read_mc_version.outputs.version }}-${{ steps.read_mod_version.outputs.version }}-server.jar
        asset_content_type: application/zip
 