on: [push]

name: BasseBombeCraft build pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: Display the path
      run: ls -la
      shell: bash

    - name: Make gradlew executable
      run: chmod +x ./gradlew
      shell: bash

    - name: Delete gradle.properties
      run: rm ./gradle.properties
      shell: bash

    - name: Build with Gradle
      run: ./gradlew build

    - name: Create Release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: true

    - name: Publish to GitHub Registry 
      run: ./gradlew publish